# For detailed information on configuring the parameter_bridge, please refer to:
# https://github.com/gazebosim/ros_gz/tree/ros2/ros_gz_bridge#example-5-configuring-the-bridge-via-yaml

- topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: ignition.msgs.Clock
  direction: GZ_TO_ROS

- ros_topic_name: battery
  gz_topic_name: model/panther/battery/battery/state
  ros_type_name: sensor_msgs/msg/BatteryState
  gz_type_name: ignition.msgs.BatteryState
  direction: GZ_TO_ROS

- ros_topic_name: _gz_lights
  gz_topic_name: /world/husarion_world/light_config
  ros_type_name: ros_gz_interfaces/msg/Light
  gz_type_name: gz.msgs.Light
  direction: ROS_TO_GZ
