chanel_1:
  position: [0.362, 0.0, 0.201]
  led_strip_width: 0.5
  topic: lights/driver/channel_1_frame
  start_id: 1 # The marker with id 0 is not modified.

chanel_2:
  position: [-0.362, 0.0, 0.201]
  led_strip_width: 0.5
  topic: lights/driver/channel_2_frame
  start_id: 47
