controller_manager:
  ros__parameters:
    use_sim_time: false
    update_rate: 25 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    panther_position_controller:
      type: position_controllers/JointGroupPositionController

    panther_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    panther_effort_controller:
      type: effort_controllers/JointGroupEffortController

panther_position_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint

panther_velocity_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint

panther_effort_controller:
  ros__parameters:
    joints:
      - fl_wheel_joint
      - fr_wheel_joint
      - rl_wheel_joint
      - rr_wheel_joint
