---
name: Release Panther project

on:
    workflow_dispatch:
        inputs:
            release-tag:
                description: Release tag
                required: true
            release-name:
                description: Release name
                required: true

jobs:
    release-panther-msgs:
        name: Release panther_msgs repository
        runs-on: ubuntu-22.04
        steps:
            - name: Trigger panther_msgs release workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.1
              with:
                  owner: husarion
                  repo: panther_msgs
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  workflow_file_name: release-repository.yaml
                  ref: ros2
                  wait_interval: 15
                  client_payload: |
                      {
                        "release-tag": "${{ github.event.inputs.release-tag }}",
                        "release-name": "${{ github.event.inputs.release-name }}"
                      }

    release-panther-ros:
        name: Release panther_ros repository
        needs: release-panther-msgs
        runs-on: ubuntu-22.04
        steps:
            - name: Trigger panther_ros release workflow
              uses: convictional/trigger-workflow-and-wait@v1.6.1
              with:
                  owner: husarion
                  repo: panther_ros
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  workflow_file_name: release-repository.yaml
                  ref: ${{ github.ref }}
                  wait_interval: 15
                  client_payload: |
                      {
                        "release-tag": "${{ github.event.inputs.release-tag }}",
                        "release-name": "${{ github.event.inputs.release-name }}"
                      }
